<?php
/**
 * Created by PhpStorm.
 * User: wang
 * Date: 2018/11/25
 * Time: 下午10:37
 */

const DISCOUNT_CARD = 'DISCOUNT';

const COUPON_CARD = 'COUPON';

const CASH_CARD = 'CASH';

const GIFT_CARD = 'GIFT';

const MEMBER_CARD = 'MEMBER_CARD';

const CARD_TYPE_COLLECTION = [
    DISCOUNT_CARD,
    COUPON_CARD,
    CASH_CARD,
    GIFT_CARD
];

const MEMBER_CARD_WAIT_ACTIVE = 'WAIT_ACTIVE';

const MEMBER_CARD_ACTIVE = 'ACTIVE';

const MEMBER_CARD_USABLE = 'USABLE';

const MEMBER_CARD_OVER_DATE = 'OVER_DATE';

const MEMBER_CARD_STATUS_COLLECTION = [
    MEMBER_CARD_WAIT_ACTIVE,
    MEMBER_CARD_ACTIVE,
    MEMBER_CARD_USABLE,
    MEMBER_CARD_OVER_DATE
];

const CARD_STATUS_UN_EFFECTIVE = 'UN_EFFECTIVE';
const CARD_STATUS_EFFECTIVE = 'EFFECTIVE';
const CARD_STATUS_USED = 'USED';
const CARD_STATUS_OVER_DATE = 'OVER_DATE';

const CARD_STATUS_COLLECTION = [
    CARD_STATUS_UN_EFFECTIVE,
    CARD_STATUS_EFFECTIVE,
    CARD_STATUS_USED,
    CARD_STATUS_OVER_DATE
];


const UNKNOWN = 'UNKNOWN';

const MALE = 'MALE';

const FEMALE = 'FEMALE';

const SEX_COLLECTION = [
    UNKNOWN,
    MALE,
    FEMALE
];

const WAIT_BUYER_PAY = 'WAIT_BUYER_PAY';

const WAIT_GROUP = 'WAIT_GROUP';

const WAIT_SELLER_SEND = 'WAIT_SELLER_SEND';

const WAIT_BUYER_SIGN = 'WAIT_BUYER_SIGN';

const BUYER_SIGNED_ORDER = 'BUYER_SIGNED_ORDER';

const BUYER_CLOSED_ORDER = 'BUYER_CLOSED_ORDER';

const SELLER_CLOSED_ORDER = 'SELLER_CLOSED_ORDER';

const AUTO_CLOSED_ORDER = 'AUTO_CLOSED_ORDER';

const ORDER_STATUS_COLLECTION = [
    WAIT_BUYER_PAY,
    WAIT_GROUP,
    WAIT_BUYER_SIGN,
    WAIT_SELLER_SEND,
    BUYER_SIGNED_ORDER,
    BUYER_CLOSED_ORDER,
    SELLER_CLOSED_ORDER,
    AUTO_CLOSED_ORDER
];

const ACTIVITY_WAIT_RUN = 'UN_START';

const ACTIVITY_RUNNING = 'RUNNING';

const ACTIVITY_OVER_DATE = 'END';

const ACTIVITY_INVALID = 'INVALID';

const ACTIVITY_STATUS_COLLECTION = [
    ACTIVITY_WAIT_RUN,
    ACTIVITY_RUNNING,
    ACTIVITY_OVER_DATE,
    ACTIVITY_INVALID
];

const ACTIVITY_TYPE_COLLECTION = [

];

const SCAN_QRCODE_SHOPPING_CART = 'SCAN_QRCODE';

const REAL_TIME_SHOPPING_CART = 'REAL_TIME';

const BOOKING_SHOPPING_CART = 'BOOKING';

const PURCHASE_SHOPPING_CART = 'PURCHASE';

const SHOPPING_CART_TYPE_COLLECTION = [
    SCAN_QRCODE_SHOPPING_CART,
    REAL_TIME_SHOPPING_CART,
    BOOKING_SHOPPING_CART,
    PURCHASE_SHOPPING_CART
];