<?php
/**
 * Created by PhpStorm.
 * User: wang
 * Date: 2018/11/25
 * Time: 下午10:37
 */

const DISCOUNT_CARD = 'DISCOUNT';

const COUPON_CARD = 'COUPON';

const CASH_CARD = 'CASH';

const GIFT_CARD = 'GIFT';

const MEMBER_CARD = 'MEMBER_CARD';

const CARD_TYPE_COLLECTION = [
    DISCOUNT_CARD,
    COUPON_CARD,
    CASH_CARD,
    GIFT_CARD
];

const MEMBER_CARD_WAIT_ACTIVE = 'WAIT_ACTIVE';

const MEMBER_CARD_ACTIVE = 'ACTIVE';

const MEMBER_CARD_USABLE = 'USABLE';

const MEMBER_CARD_OVER_DATE = 'OVER_DATE';

const MEMBER_CARD_STATUS_COLLECTION = [
    MEMBER_CARD_WAIT_ACTIVE,
    MEMBER_CARD_ACTIVE,
    MEMBER_CARD_USABLE,
    MEMBER_CARD_OVER_DATE
];

const CARD_STATUS_UN_EFFECTIVE = 'UN_EFFECTIVE';
const CARD_STATUS_EFFECTIVE = 'EFFECTIVE';
const CARD_STATUS_USED = 'USED';
const CARD_STATUS_OVER_DATE = 'OVER_DATE';

const CARD_STATUS_COLLECTION = [
    CARD_STATUS_UN_EFFECTIVE,
    CARD_STATUS_EFFECTIVE,
    CARD_STATUS_USED,
    CARD_STATUS_OVER_DATE
];


const UNKNOWN = 'UNKNOWN';

const MALE = 'MALE';

const FEMALE = 'FEMALE';

const SEX_COLLECTION = [
    UNKNOWN,
    MALE,
    FEMALE
];

const WAIT_BUYER_PAY = 'WAIT_BUYER_PAY';

const WAIT_GROUP = 'WAIT_GROUP';

const WAIT_SELLER_SEND = 'WAIT_SELLER_SEND';

const WAIT_BUYER_SIGN = 'WAIT_BUYER_SIGN';

const BUYER_SIGNED_ORDER = 'BUYER_SIGNED_ORDER';

const BUYER_CLOSED_ORDER = 'BUYER_CLOSED_ORDER';

const SELLER_CLOSED_ORDER = 'SELLER_CLOSED_ORDER';

const AUTO_CLOSED_ORDER = 'AUTO_CLOSED_ORDER';

const ORDER_STATUS_COLLECTION = [
    WAIT_BUYER_PAY,
    WAIT_GROUP,
    WAIT_BUYER_SIGN,
    WAIT_SELLER_SEND,
    BUYER_SIGNED_ORDER,
    BUYER_CLOSED_ORDER,
    SELLER_CLOSED_ORDER,
    AUTO_CLOSED_ORDER
];

const ACTIVITY_WAIT_RUN = 'UN_START';

const ACTIVITY_RUNNING = 'RUNNING';

const ACTIVITY_OVER_DATE = 'END';

const ACTIVITY_INVALID = 'INVALID';

const ACTIVITY_STATUS_COLLECTION = [
    ACTIVITY_WAIT_RUN,
    ACTIVITY_RUNNING,
    ACTIVITY_OVER_DATE,
    ACTIVITY_INVALID
];

const ACTIVITY_TYPE_COLLECTION = [

];

const SCAN_QRCODE_SHOPPING_CART = 'SCAN_QRCODE';

const REAL_TIME_SHOPPING_CART = 'REAL_TIME';

const BOOKING_SHOPPING_CART = 'BOOKING';

const PURCHASE_SHOPPING_CART = 'PURCHASE';

const SHOPPING_CART_TYPE_COLLECTION = [
    SCAN_QRCODE_SHOPPING_CART,
    REAL_TIME_SHOPPING_CART,
    BOOKING_SHOPPING_CART,
    PURCHASE_SHOPPING_CART
];

//const WAIT_PAY_ORDER = 'WAIT_PAY';// 待支付
//const PAID_ORDER = 'PAID';// 已支付
//const SEND_ORDER = 'SEND';// 已配送
//const SIGNED_ORDER = 'SIGNED';// 已签收
//const CANCEL_ORDER = 'CANCEL'; // 订单关闭
//const COMPLETED_ORDER = 'COMPLETED';// 订单完成

//const ORDER_STATUS_COLLECTION = [
//    WAIT_PAY_ORDER,
//    PAID_ORDER,
//    SEND_ORDER,
//    SIGNED_ORDER,
//    CANCEL_ORDER,
//    COMPLETED_ORDER
//];
const SCAN_QR_CODE_ORDER = 'SCAN_QR_CODE';// 线下扫码聚合支付订单
const BOOKING_ORDER = 'BOOKING';// 预订单
const SCAN_CODE_INSTANT_ORDER = 'SCAN_CODE_INSTANT';// 新零售扫码即时订单
const ONLINE_INSTANT_ORDER = 'ONLINE_INSTANT';// 线上及时购
const PURCHASE_ORDER = 'PURCHASE';// 采购订单
const CHARGE_ORDER = 'CHARGE';// 充值
const TB_ORDER = 'TB_ORDER';
const TM_ORDER = 'TM_ORDER';
const JD_ORDER = 'JD_ORDER';
const MT_ORDER = 'MT_ORDER';
const ELM_ORDER = 'ELM_ORDER';
const ORDER_TYPE_COLLECTION = [
    SCAN_QR_CODE_ORDER,
    BOOKING_ORDER,
    SCAN_CODE_INSTANT_ORDER,
    ONLINE_INSTANT_ORDER,
    PURCHASE_ORDER,
    CHARGE_ORDER,
    TB_ORDER,
    TM_ORDER,
    JD_ORDER,
    MT_ORDER,
    ELM_ORDER
];

const WAIT_REFUND_ORDER = 'WAIT_REFUND';
const REFUSED_REFUND_ORDER = 'REFUSED_REFUND';
const COMPLETED_REFUND_ORDER = 'COMPLETED_REFUND';

const REFUND_ORDER_COLLECTION = [
    WAIT_REFUND_ORDER,
    REFUSED_REFUND_ORDER,
    COMPLETED_REFUND_ORDER
];


const ONLINE_SHOPPING_MALL = 'ONLINE_SHOPPING_MALL';// 线上商城
const CHAIN_CVS_STORE = 'CHAIN_CVS';// 连锁便利店
const RETAIL_STORE = 'RETAIL';// 零售店
const SALON_STORE = 'SALON';// 发廊、美容
const CHAIN_SALON_STORE = 'CHAIN_SALON';// 连锁美容美发
const RESTAURANT_STORE = 'RESTAURANT';// 餐馆
const CHAIN_RESTAURANT_STORE = 'CHAIN_RESTAURANT';// 连锁餐馆

const STORE_TYPE_COLLECTION = [
    ONLINE_SHOPPING_MALL,
    CHAIN_CVS_STORE,
    RETAIL_STORE,
    CHAIN_SALON_STORE,
    SALON_STORE,
    CHAIN_RESTAURANT_STORE,
    RESTAURANT_STORE
];

const WECHAT_OFFICIAL_ACCOUNT_USER = 'WECHAT_OFFICIAL_ACCOUNT';
const ALI_LIFE_ACCOUNT_USER = 'ALI_LIFE_ACCOUNT';
const WECHAT_MINI_PROGRAM_USER = 'WECHAT_MINI_PROGRAM';
const ALI_MINI_PROGRAM_USER = 'ALI_MINI_PROGRAM';
const TENCENT_QQ_USER = 'TENCENT_QQ';
const SINA_OPEN_USER = 'SINA_OPEN';
const FACEBOOK_USER = 'FACEBOOK';
const TWITTER_USER = 'TWITTER';
const PLATFORM_TYPE_COLLECTION = [
    WECHAT_OFFICIAL_ACCOUNT_USER,
    WECHAT_MINI_PROGRAM_USER,
    ALI_LIFE_ACCOUNT_USER,
    ALI_MINI_PROGRAM_USER,
    TENCENT_QQ_USER,
    SINA_OPEN_USER,
    FACEBOOK_USER,
    TWITTER_USER
];

const WECHAT_CONFIG_TYPE_COLLECTION = [
    WECHAT_OFFICIAL_ACCOUNT_USER,
    WECHAT_MINI_PROGRAM_USER
];

const PLATFORM_MEMBER_CARD = 'PLATFORM_MEMBER_CARD';

const STORE_MEMBER_CARD = 'STORE_MEMBER_CARD';

const MEMBER_CARD_TYPE_COLLECTION = [
    PLATFORM_MEMBER_CARD,
    STORE_MEMBER_CARD
];

//const ACTIVITY_WAIT = 'ACTIVITY_WAIT';
//const ACTIVITY_RUNNING = 'ACTIVITY_RUNNING';
//const ACTIVITY_OVER_DATE = 'ACTIVITY_OVER_DATE';
//const ACTIVITY_INVALID = 'ACTIVITY_INVALID';
//
//const ACTIVITY_STATUS_COLLECTION = [
//    ACTIVITY_INVALID,
//    ACTIVITY_OVER_DATE,
//    ACTIVITY_RUNNING,
//    ACTIVITY_WAIT
//];
