<?php
/**
 * Created by PhpStorm.
 * User: wang
 * Date: 2018/11/25
 * Time: 下午10:37
 */

const DISCOUNT_CARD = 'discount';

const COUPON_CARD = 'coupon';

const CASH_CARD = 'cash';

const GIFT_CARD = 'gift';

const MEMBER_CARD = 'member_card';

const CARD_TYPE_COLLECTION = [
    DISCOUNT_CARD,
    COUPON_CARD,
    CASH_CARD,
    GIFT_CARD
];

const CARD_STATUS_UN_EFFECTIVE = 'un_effective';
const CARD_STATUS_EFFECTIVE = 'effective';
const CARD_STATUS_USED = 'used';
const CARD_STATUS_OVER_DATE = 'over_date';

const CARD_STATUS_COLLECTION = [
    CARD_STATUS_UN_EFFECTIVE,
    CARD_STATUS_EFFECTIVE,
    CARD_STATUS_USED,
    CARD_STATUS_OVER_DATE
];

const WAIT_PAY_ORDER = 'WAIT_PAY';// 待支付
const PAID_ORDER = 'PAID';// 已支付
const SEND_ORDER = 'SEND';// 已配送
const SIGNED_ORDER = 'SIGNED';// 已签收
const CANCEL_ORDER = 'CANCEL'; // 订单关闭
const COMPLETED_ORDER = 'COMPLETED';// 订单完成

const ORDER_STATUS_COLLECTION = [
    WAIT_PAY_ORDER,
    PAID_ORDER,
    SEND_ORDER,
    SIGNED_ORDER,
    CANCEL_ORDER,
    COMPLETED_ORDER
];
const SCAN_QR_CODE_ORDER = 'SCAN_QR_CODE';// 线下扫码聚合支付订单
const BOOKING_ORDER = 'BOOKING';// 预订单
const SCAN_CODE_INSTANT_ORDER = 'SCAN_CODE_INSTANT';// 新零售扫码即时订单
const ONLINE_INSTANT_ORDER = 'ONLINE_INSTANT';// 线上及时购
const PURCHASE_ORDER = 'PURCHASE';// 采购订单
const CHARGE_ORDER = 'CHARGE';// 充值
const ORDER_TYPE_COLLECTION = [
    SCAN_QR_CODE_ORDER,
    BOOKING_ORDER,
    SCAN_CODE_INSTANT_ORDER,
    ONLINE_INSTANT_ORDER,
    PURCHASE_ORDER,
    CHARGE_ORDER
];

const WAIT_REFUND_ORDER = 'WAIT_REFUND';
const REFUSED_REFUND_ORDER = 'REFUSED_REFUND';
const COMPLETED_REFUND_ORDER = 'COMPLETED_REFUND';

const REFUND_ORDER_COLLECTION = [
    WAIT_REFUND_ORDER,
    REFUSED_REFUND_ORDER,
    COMPLETED_REFUND_ORDER
];


const ONLINE_SHOPPING_MALL = 'ONLINE_SHOPPING_MALL';// 线上商城
const CHAIN_CVS_STORE = 'CHAIN_CVS';// 连锁便利店
const RETAIL_STORE = 'RETAIL';// 零售店
const SALON_STORE = 'SALON';// 发廊、美容
const CHAIN_SALON_STORE = 'CHAIN_SALON';// 连锁美容美发
const RESTAURANT_STORE = 'RESTAURANT';// 餐馆
const CHAIN_RESTAURANT_STORE = 'CHAIN_RESTAURANT';// 连锁餐馆

const STORE_TYPE_COLLECTION = [
    ONLINE_SHOPPING_MALL,
    CHAIN_CVS_STORE,
    RETAIL_STORE,
    CHAIN_SALON_STORE,
    SALON_STORE,
    CHAIN_RESTAURANT_STORE,
    RESTAURANT_STORE
];

const WECHAT_OFFICIAL_ACCOUNT_USER = 'WECHAT_OFFICIAL_ACCOUNT';
const ALI_LIFE_ACCOUNT_USER = 'ALI_LIFE_ACCOUNT';
const WECHAT_MINI_PROGRAM_USER = 'WECHAT_MINI_PROGRAM';
const ALI_MINI_PROGRAM_USER = 'ALI_MINI_PROGRAM';
const TENCENT_QQ_USER = 'TENCENT_QQ';
const SINA_OPEN_USER = 'SINA_OPEN';
const FACEBOOK_USER = 'FACEBOOK';
const TWITTER_USER = 'TWITTER';
const PLATFORM_TYPE_COLLECTION = [
    WECHAT_OFFICIAL_ACCOUNT_USER,
    WECHAT_MINI_PROGRAM_USER,
    ALI_LIFE_ACCOUNT_USER,
    ALI_MINI_PROGRAM_USER,
    TENCENT_QQ_USER,
    SINA_OPEN_USER,
    FACEBOOK_USER,
    TWITTER_USER
];

const PLATFORM_MEMBER_CARD = 'PLATFORM_MEMBER_CARD';

const STORE_MEMBER_CARD = 'STORE_MEMBER_CARD';

const MEMBER_CARD_TYPE_COLLECTION = [
    PLATFORM_MEMBER_CARD,
    STORE_MEMBER_CARD
];
